services:
  ecommerce-db:
    image: postgres:latest
    container_name: ecommerce-db
    environment:
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: ecommerce
      POSTGRES_DB: ecommerce
    ports:
      - "5434:5432"
    volumes:
      - ecommerce_data:/var/lib/postgresql/data

  vault:
    image: hashicorp/vault:1.14.0
    container_name: ecommerce-vault
    restart: always
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_ADDR: "http://127.0.0.1:8200"
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -dev -dev-root-token-id="root" -dev-listen-address="0.0.0.0:8200"
    volumes:
      - vault_data:/vault/file

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonar-postgres:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar

  sonar-postgres:
    image: postgres:latest
    container_name: sonar-postgres
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"

  keycloak-db:
    image: postgres:latest
    container_name: keycloak-db
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    container_name: keycloak
    command: start-dev --db=postgres --db-url=jdbc:postgresql://keycloak-db:5432/keycloak --db-username=keycloak --db-password=keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db

volumes:
  keycloak_data:
  ecommerce_data:
  vault_data:
