version: "3.8"

services:
  #i will use my own oracle
  #oracle-db:
    #image: gvenzl/oracle-xe:latest
    #container_name: oracle-db
    #environment:
    #  - ORACLE_PASSWORD=ecommerce_password
    #  - ORACLE_DATABASE=ecommerce
    #ports:
     # - "1521:1521"
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonar-postgres:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar

  sonar-postgres:
      image: postgres:latest
      container_name: sonar-postgres
      environment:
        POSTGRES_USER: sonar
        POSTGRES_PASSWORD: sonar
        POSTGRES_DB: sonar
      ports:
        - "5432:5432"
  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"

  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    container_name: keycloak
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"