server:
  port : 8081

spring:
  datasource :
    url: jdbc:postgresql://localhost:5434/ecommerce  # Change database name as needed
    username: ecommerce
    password: ecommerce
    driver-class-name: org.postgresql.Driver
  jpa:
    database-plateform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ecommerce-realm
keycloak:
  auth-server-url: http://localhost:8080
  realm: ecommerce-realm
  resource: ecommerce-client
  credentials:
    secret: sxQZ9AJcnnEcYMB2QJftnqOQG58021SP
  use-resource-role-mappings: true