server:
  port : 8081

spring:
  application:
    name: user-service
  cloud:
    vault:
      uri: http://localhost:8200
      token: hvs.DE1RjALM3efDnV0XrmwvPO18
      kv:
        enabled: true
        backend: secret
        application-name: ${spring.application.name}
  flyway:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5434/ecommerce
    username: ecommerce
    password: ecommerce
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ecommerce-realm
          jwk-set-uri: http://localhost:8080/realms/ecommerce-realm/protocol/openid-connect/certs