server:
  port : 8081

spring:
  cloud:
    vault:
      uri: http://localhost:8200
      authentication: TOKEN
      token: root
      kv:
        enabled: true
  datasource :
    url: jdbc:postgresql://localhost:5434/ecommerce ${vault}
    username: ${vault:secret/ecommerce-db/username}
    password: ${vault:secret/ecommerce-db/password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  flyway:
    enabled: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ecommerce-realm
keycloak:
  auth-server-url: http://localhost:8080
  realm: ecommerce-realm
  resource: ecommerce-client
  credentials:
    secret: sxQZ9AJcnnEcYMB2QJftnqOQG58021SP
  use-resource-role-mappings: true