server:
  port: 8082
spring:
  cache:
    type: redis
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ecommerce-realm
          jwk-set-uri: http://localhost:8080/realms/ecommerce-realm/protocol/openid-connect/certs
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000
  datasource:
    url: jdbc:postgresql://localhost:5434/ecommerce
    username: ecommerce
    password: ecommerce
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate