server:
  port: 8085
spring:
  application:
    name: gateway
  datasource:
    url: jdbc:postgresql://localhost:5434/ecommerce
    username: ${db.username}
    password: ${db.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-plateform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    out-of-order: true
    validateMigrationNaming: true
  cloud:
    vault:
      uri: http://localhost:8200
      token: hvs.DE1RjALM3efDnV0XrmwvPO18
      kv:
        enabled: true
        backend: secret
        application-name: ${spring.application.name}
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/ecommerce/users/**
          filters:
            - TokenRelay

        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/ecommerce/products/**
          filters:
            - TokenRelay

        - id: cart-service
          uri: http://localhost:8086
          predicates:
            - Path=/ecommerce/cart/**
          filters:
            - TokenRelay

        - id: order-service
          uri: http://localhost:8087
          predicates:
            - Path=/ecommerce/order/**
          filters:
            - TokenRelay

        - id: checkout-service
          uri: http://localhost:8088
          predicates:
            - Path=/ecommerce/checkout/**
          filters:
            - TokenRelay

        - id: payment-service
          uri: http://localhost:8088
          predicates:
            - Path=/ecommerce/payment/**
          filters:
            - TokenRelay
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ecommerce-realm
          jwk-set-uri: http://localhost:8080/realms/ecommerce-realm/protocol/openid-connect/certs

      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/ecommerce-realm
            jwk-set-uri: http://localhost:8080/realms/ecommerce-realm/protocol/openid-connect/certs
        registration:
          ecommerce-client:
            provider: keycloak
            client-id: ecommerce-client
            client-secret: ${keycloack.client.secret}
            authorization-grant-type: client_credentials