spring:
  datasource :
    url: jdbc:postgresql://localhost:5434/ecommerce  # Change database name as needed
    username: ecommerce
    password: ecommerce
    driver-class-name: org.postgresql.Driver
  jpa:
    database-plateform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    out-of-order: true
    validateMigrationNaming: true